[package]
name = "play"
version = "0.1.0"
authors = ["Mikhail Katychev <mkatych@gmail.com>"]
edition = "2021"
[lib]
crate-type = ["cdylib", "rlib"]


[dependencies]
napi = { version = "2.16.8", features = ["serde-json"] }
serde_json = "1.0.118"
wasm-bindgen = "0.2.93"
