[package]
name = "play"
version = "0.1.0"
authors = ["Mikhail Katychev <mkatych@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.28"
signal-hook = "0.3.15"
tokio = { version = "1.26.0", features = ["rt", "rt-multi-thread", "macros", "sync", "time"] }


